version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextApp
    command: npm start
    ports:
      - "8443:3210"
    volumes:
      - .:/app
      - /app/node-modules
    expose:
      - "3210"
    